version: '3.8'

services:
  # CPU Serving service (chạy trên CPU Droplet)
  embedding-server:
    build:
      context: .
      dockerfile: Dockerfile.serving
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT:-https://sgp1.digitaloceanspaces.com}
      - SPACES_BUCKET=${SPACES_BUCKET:-legal-datalake}
      - MODEL_PATH=${MODEL_PATH}
      - PORT=5000
    volumes:
      - ./models:/tmp/model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Nginx reverse proxy (optional cho production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - embedding-server
    restart: unless-stopped
    profiles:
      - production  # Chỉ start khi dùng profile production

volumes:
  model_data:
    driver: local